//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieInfo
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Rating { get; set; }
        public string Director { get; set; }
        public string Cast { get; set; }
        public Nullable<int> Year { get; set; }
        public string Genre { get; set; }
        public Nullable<int> Duration { get; set; }
        public byte[] Image { get; set; }
    }
}
